"""Generate 50 strategies by combining archetypes x asset classes.

ARCHITECTURAL CONSTRAINT:
- Strategies are CONFIG, not code. Expanding means adding entries here, not new
  engine code paths. The EventDrivenStrategyEngine is parameterised.
- All instrument references MUST exist in UAC representative_sample.py.
- The original 18 strategies (strat-001..018) MUST keep their IDs for Dashboard
  visual parity. Do NOT rename or remove them.
- SSOT: unified-trading-codex/09-strategy/ for archetypes.

Imported by seed.py. Preserves the original 18 strategies (strat-001 through
strat-018) and adds 32 new strategies following the naming convention
``{ASSET}_{ARCHETYPE}_{MODE}_{TIMEFRAME}``.

Distribution:
  - Asset class: CeFi 16, TradFi 11, DeFi 11, Sports 9, Prediction 3 = 50
  - Org: odum-internal 60%, acme 20%, vertex 12%, beta 8%
  - Status: ~65% live, ~15% staging, ~10% paper, ~10% development
"""

from __future__ import annotations

from typing import Final

# ── Org aliases ───────────────────────────────────────────────────────
_O: Final[str] = "odum-internal"
_A: Final[str] = "acme"
_V: Final[str] = "vertex"
_B: Final[str] = "beta"

# ── Client IDs per org ────────────────────────────────────────────────
_CLIENT_ODUM: Final[str] = "client-odum-desk"
_CLIENT_ACME: Final[str] = "client-acme-alpha"
_CLIENT_VERTEX: Final[str] = "client-vertex-partners"
_CLIENT_BETA: Final[str] = "client-beta-fund"

# ── Archetype catalogue (15 documented) ──────────────────────────────
# CeFi:   momentum, mean-reversion, market-making
# TradFi: ml-directional, options-ml, market-making-options
# DeFi:   basis-trade, staked-basis, recursive-staked-basis,
#         aave-lending, amm-lp
# Sports: arbitrage, value-betting, ml-sports, market-making


def _legacy_strategies() -> list[dict[str, object]]:
    """Original 18 strategies (strat-001 .. strat-018) — exact same IDs/names."""
    return [
        # ── strat-001 .. strat-008 (original 8) ──────────────────────
        {
            "id": "strat-001",
            "name": "DEFI_ETH_BASIS_SCE_1H",
            "asset_class": "defi",
            "venue": "uniswap_v3",
            "status": "live",
            "version": "2.1.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "basis-trade",
            "inception_date": "2025-03-01",
            "instruments": ["ETH/USDC", "WETH/USDT"],
        },
        {
            "id": "strat-002",
            "name": "CEFI_BTC_ML_DIR_HUF_4H",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "live",
            "version": "3.4.1",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "quant-fund",
            "archetype": "momentum",
            "inception_date": "2024-11-15",
            "instruments": ["BTC/USDT", "BTC/USDC"],
        },
        {
            "id": "strat-003",
            "name": "CEFI_ETH_OPT_MM_EVT_TICK",
            "asset_class": "cefi",
            "venue": "deribit",
            "status": "live",
            "version": "1.8.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "market-making",
            "inception_date": "2025-01-10",
            "instruments": ["ETH-PERP", "ETH-20260327-C-4000"],
        },
        {
            "id": "strat-004",
            "name": "CEFI_BTC_MM_HUF_15S",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "live",
            "version": "4.0.2",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "quant-fund",
            "archetype": "market-making",
            "inception_date": "2024-09-01",
            "instruments": ["BTC/USDT"],
        },
        {
            "id": "strat-005",
            "name": "TRADFI_ES_STAT_ARB_SCE_5M",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "staging",
            "version": "0.9.3",
            "org_id": _V,
            "client_id": _CLIENT_VERTEX,
            "desk": "quant-fund",
            "archetype": "ml-directional",
            "inception_date": "2025-06-20",
            "instruments": ["ES", "NQ"],
        },
        {
            "id": "strat-006",
            "name": "CEFI_MULTI_MOM_HUF_1H",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "live",
            "version": "2.3.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "momentum",
            "inception_date": "2025-02-14",
            "instruments": ["BTC/USDT", "ETH/USDT", "SOL/USDT"],
        },
        {
            "id": "strat-007",
            "name": "DEFI_AAVE_YIELD_EVT_BLOCK",
            "asset_class": "defi",
            "venue": "aave_v3",
            "status": "live",
            "version": "1.2.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "defi",
            "archetype": "aave-lending",
            "inception_date": "2025-04-05",
            "instruments": ["WETH", "USDC", "DAI"],
        },
        {
            "id": "strat-008",
            "name": "SPORTS_NFL_ARB_EVT_GAME",
            "asset_class": "sports",
            "venue": "betfair",
            "status": "live",
            "version": "1.5.1",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "sports",
            "archetype": "arbitrage",
            "inception_date": "2025-01-25",
            "instruments": ["NFL_MONEYLINE", "NFL_SPREAD"],
        },
        # ── strat-009 .. strat-018 (additional 10) ───────────────────
        {
            "id": "strat-009",
            "name": "CEFI_SOL_PERP_TREND_HUF_30M",
            "asset_class": "cefi",
            "venue": "hyperliquid",
            "status": "live",
            "version": "1.1.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "momentum",
            "inception_date": "2025-05-10",
            "instruments": ["SOL-PERP"],
        },
        {
            "id": "strat-010",
            "name": "DEFI_UNI_LP_REBAL_SCE_1H",
            "asset_class": "defi",
            "venue": "uniswap_v3",
            "status": "staging",
            "version": "0.7.2",
            "org_id": _V,
            "client_id": _CLIENT_VERTEX,
            "desk": "defi",
            "archetype": "amm-lp",
            "inception_date": "2025-07-01",
            "instruments": ["ETH/USDC", "WBTC/ETH"],
        },
        {
            "id": "strat-011",
            "name": "CEFI_ETH_FUNDING_ARB_HUF_8H",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "live",
            "version": "2.0.1",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "quant-fund",
            "archetype": "mean-reversion",
            "inception_date": "2025-03-20",
            "instruments": ["ETH/USDT", "ETH-PERP"],
        },
        {
            "id": "strat-012",
            "name": "SPORTS_EPL_ML_DIR_EVT_MATCH",
            "asset_class": "sports",
            "venue": "betfair",
            "status": "live",
            "version": "3.1.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "sports",
            "archetype": "ml-sports",
            "inception_date": "2024-08-15",
            "instruments": ["EPL_MATCH_ODDS", "EPL_OVER_UNDER"],
        },
        {
            "id": "strat-013",
            "name": "TRADFI_NQ_MOM_SCE_15M",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "paper",
            "version": "0.5.0",
            "org_id": _B,
            "client_id": _CLIENT_BETA,
            "desk": "quant-fund",
            "archetype": "ml-directional",
            "inception_date": "2025-09-01",
            "instruments": ["NQ"],
        },
        {
            "id": "strat-014",
            "name": "CEFI_MULTI_VOL_SURF_EVT_1H",
            "asset_class": "cefi",
            "venue": "deribit",
            "status": "live",
            "version": "1.9.4",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "delta-one",
            "archetype": "mean-reversion",
            "inception_date": "2025-02-28",
            "instruments": ["BTC-PERP", "ETH-PERP"],
        },
        {
            "id": "strat-015",
            "name": "DEFI_FLASH_LOAN_ARB_EVT_BLOCK",
            "asset_class": "defi",
            "venue": "aave_v3",
            "status": "paper",
            "version": "0.3.1",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "defi",
            "archetype": "recursive-staked-basis",
            "inception_date": "2025-08-10",
            "instruments": ["WETH", "WSTETH", "USDC"],
        },
        {
            "id": "strat-016",
            "name": "SPORTS_NBA_LIVE_EVT_QUARTER",
            "asset_class": "sports",
            "venue": "matchbook",
            "status": "staging",
            "version": "0.8.0",
            "org_id": _B,
            "client_id": _CLIENT_BETA,
            "desk": "sports",
            "archetype": "value-betting",
            "inception_date": "2025-10-01",
            "instruments": ["NBA_MONEYLINE", "NBA_TOTAL"],
        },
        {
            "id": "strat-017",
            "name": "CEFI_BTC_GRID_HUF_5M",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "paper",
            "version": "0.4.0",
            "org_id": _V,
            "client_id": _CLIENT_VERTEX,
            "desk": "delta-one",
            "archetype": "market-making",
            "inception_date": "2025-11-01",
            "instruments": ["BTC/USDT"],
        },
        {
            "id": "strat-018",
            "name": "PREDICTION_POLY_SENT_EVT_1H",
            "asset_class": "prediction",
            "venue": "polymarket",
            "status": "live",
            "version": "1.0.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "quant-fund",
            "archetype": "value-betting",
            "inception_date": "2025-06-01",
            "instruments": ["POLY_PRESIDENTIAL_2028", "POLY_FED_RATE"],
        },
    ]


def _new_strategies() -> list[dict[str, object]]:
    """32 new strategies (strat-019 .. strat-050) across all asset classes."""
    return [
        # ══════════════════════════════════════════════════════════════
        #  CeFi — 6 new (16 total with 10 legacy)
        # ══════════════════════════════════════════════════════════════
        {
            "id": "strat-019",
            "name": "CEFI_AVAX_MOMENTUM_HUF_1H",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "live",
            "version": "1.3.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "momentum",
            "inception_date": "2025-04-12",
            "instruments": ["AVAX/USDT"],
        },
        {
            "id": "strat-020",
            "name": "CEFI_ETH_MEAN_REV_SCE_4H",
            "asset_class": "cefi",
            "venue": "okx",
            "status": "live",
            "version": "2.0.0",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "quant-fund",
            "archetype": "mean-reversion",
            "inception_date": "2025-01-20",
            "instruments": ["ETH/USDT", "ETH/USDC"],
        },
        {
            "id": "strat-021",
            "name": "CEFI_DOGE_MM_HUF_30S",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "live",
            "version": "1.0.1",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "market-making",
            "inception_date": "2025-06-15",
            "instruments": ["DOGE/USDT"],
        },
        {
            "id": "strat-022",
            "name": "CEFI_LINK_MOMENTUM_SCE_2H",
            "asset_class": "cefi",
            "venue": "hyperliquid",
            "status": "staging",
            "version": "0.6.0",
            "org_id": _V,
            "client_id": _CLIENT_VERTEX,
            "desk": "delta-one",
            "archetype": "momentum",
            "inception_date": "2025-08-01",
            "instruments": ["LINK-PERP"],
        },
        {
            "id": "strat-023",
            "name": "CEFI_ARB_MEAN_REV_HUF_15M",
            "asset_class": "cefi",
            "venue": "okx",
            "status": "development",
            "version": "0.1.0",
            "org_id": _B,
            "client_id": _CLIENT_BETA,
            "desk": "quant-fund",
            "archetype": "mean-reversion",
            "inception_date": "2026-01-10",
            "instruments": ["ARB/USDT"],
        },
        {
            "id": "strat-024",
            "name": "CEFI_XRP_MM_HUF_1M",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "live",
            "version": "1.7.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "market-making",
            "inception_date": "2025-05-22",
            "instruments": ["XRP/USDT"],
        },
        # ══════════════════════════════════════════════════════════════
        #  TradFi — 9 new (11 total with 2 legacy)
        # ══════════════════════════════════════════════════════════════
        {
            "id": "strat-025",
            "name": "TRADFI_ES_ML_DIR_SCE_30M",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "live",
            "version": "2.2.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "quant-fund",
            "archetype": "ml-directional",
            "inception_date": "2025-01-05",
            "instruments": ["ES"],
        },
        {
            "id": "strat-026",
            "name": "TRADFI_SPY_OPTIONS_ML_EVT_1D",
            "asset_class": "tradfi",
            "venue": "cboe",
            "status": "live",
            "version": "1.4.0",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "quant-fund",
            "archetype": "options-ml",
            "inception_date": "2024-10-15",
            "instruments": ["SPY", "SPY-C-500-20260320"],
        },
        {
            "id": "strat-027",
            "name": "TRADFI_CL_ML_DIR_SCE_1H",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "live",
            "version": "1.9.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "quant-fund",
            "archetype": "ml-directional",
            "inception_date": "2025-02-01",
            "instruments": ["CL", "BZ"],
        },
        {
            "id": "strat-028",
            "name": "TRADFI_GC_MM_OPTIONS_EVT_TICK",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "live",
            "version": "3.0.1",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "market-making-options",
            "inception_date": "2024-12-01",
            "instruments": ["GC", "GC-C-2500-20260617"],
        },
        {
            "id": "strat-029",
            "name": "TRADFI_ZN_OPTIONS_ML_SCE_4H",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "staging",
            "version": "0.8.1",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "quant-fund",
            "archetype": "options-ml",
            "inception_date": "2025-07-15",
            "instruments": ["ZN", "ZN-P-110-20260918"],
        },
        {
            "id": "strat-030",
            "name": "TRADFI_SI_ML_DIR_SCE_2H",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "live",
            "version": "1.1.0",
            "org_id": _V,
            "client_id": _CLIENT_VERTEX,
            "desk": "quant-fund",
            "archetype": "ml-directional",
            "inception_date": "2025-04-20",
            "instruments": ["SI"],
        },
        {
            "id": "strat-031",
            "name": "TRADFI_QQQ_MM_OPTIONS_EVT_5M",
            "asset_class": "tradfi",
            "venue": "cboe",
            "status": "paper",
            "version": "0.3.0",
            "org_id": _B,
            "client_id": _CLIENT_BETA,
            "desk": "delta-one",
            "archetype": "market-making-options",
            "inception_date": "2025-11-10",
            "instruments": ["QQQ", "QQQ-C-480-20260320"],
        },
        {
            "id": "strat-032",
            "name": "TRADFI_EURUSD_ML_DIR_SCE_1H",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "live",
            "version": "2.5.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "quant-fund",
            "archetype": "ml-directional",
            "inception_date": "2024-06-01",
            "instruments": ["6E"],
        },
        {
            "id": "strat-033",
            "name": "TRADFI_HG_OPTIONS_ML_SCE_1D",
            "asset_class": "tradfi",
            "venue": "cme",
            "status": "development",
            "version": "0.1.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "quant-fund",
            "archetype": "options-ml",
            "inception_date": "2026-02-01",
            "instruments": ["HG"],
        },
        # ══════════════════════════════════════════════════════════════
        #  DeFi — 7 new (11 total with 4 legacy)
        # ══════════════════════════════════════════════════════════════
        {
            "id": "strat-034",
            "name": "DEFI_WBTC_BASIS_SCE_4H",
            "asset_class": "defi",
            "venue": "uniswap_v3",
            "status": "live",
            "version": "1.5.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "defi",
            "archetype": "basis-trade",
            "inception_date": "2025-03-15",
            "instruments": ["WBTC/USDC", "WBTC/ETH"],
        },
        {
            "id": "strat-035",
            "name": "DEFI_STETH_STAKED_BASIS_EVT_1D",
            "asset_class": "defi",
            "venue": "lido",
            "status": "live",
            "version": "2.0.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "defi",
            "archetype": "staked-basis",
            "inception_date": "2025-02-10",
            "instruments": ["STETH", "WSTETH", "ETH"],
        },
        {
            "id": "strat-036",
            "name": "DEFI_ETH_RECURSIVE_STAKED_EVT_BLOCK",
            "asset_class": "defi",
            "venue": "aave_v3",
            "status": "live",
            "version": "1.0.0",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "defi",
            "archetype": "recursive-staked-basis",
            "inception_date": "2025-05-01",
            "instruments": ["WSTETH", "WETH", "USDC"],
        },
        {
            "id": "strat-037",
            "name": "DEFI_USDC_AAVE_LEND_EVT_1H",
            "asset_class": "defi",
            "venue": "aave_v3",
            "status": "live",
            "version": "1.8.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "defi",
            "archetype": "aave-lending",
            "inception_date": "2025-01-15",
            "instruments": ["USDC", "USDT", "DAI"],
        },
        {
            "id": "strat-038",
            "name": "DEFI_ARB_AMM_LP_SCE_4H",
            "asset_class": "defi",
            "venue": "uniswap_v3",
            "status": "staging",
            "version": "0.5.0",
            "org_id": _V,
            "client_id": _CLIENT_VERTEX,
            "desk": "defi",
            "archetype": "amm-lp",
            "inception_date": "2025-09-10",
            "instruments": ["ARB/USDC", "ARB/ETH"],
        },
        {
            "id": "strat-039",
            "name": "DEFI_MATIC_AMM_LP_SCE_2H",
            "asset_class": "defi",
            "venue": "uniswap_v3",
            "status": "development",
            "version": "0.2.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "defi",
            "archetype": "amm-lp",
            "inception_date": "2026-01-05",
            "instruments": ["MATIC/USDC"],
        },
        {
            "id": "strat-040",
            "name": "DEFI_DAI_AAVE_LEND_EVT_8H",
            "asset_class": "defi",
            "venue": "aave_v3",
            "status": "live",
            "version": "1.3.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "defi",
            "archetype": "aave-lending",
            "inception_date": "2025-04-20",
            "instruments": ["DAI", "USDC"],
        },
        # ══════════════════════════════════════════════════════════════
        #  Sports — 6 new (9 total with 3 legacy)
        # ══════════════════════════════════════════════════════════════
        {
            "id": "strat-041",
            "name": "SPORTS_EPL_ARB_EVT_MATCH",
            "asset_class": "sports",
            "venue": "betfair",
            "status": "live",
            "version": "2.4.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "sports",
            "archetype": "arbitrage",
            "inception_date": "2024-09-15",
            "instruments": ["EPL_MATCH_ODDS", "EPL_ASIAN_HANDICAP"],
        },
        {
            "id": "strat-042",
            "name": "SPORTS_NFL_VALUE_BET_EVT_GAME",
            "asset_class": "sports",
            "venue": "betfair",
            "status": "live",
            "version": "1.6.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "sports",
            "archetype": "value-betting",
            "inception_date": "2025-01-01",
            "instruments": ["NFL_MONEYLINE", "NFL_TOTAL"],
        },
        {
            "id": "strat-043",
            "name": "SPORTS_LALIGA_ML_EVT_MATCH",
            "asset_class": "sports",
            "venue": "betfair",
            "status": "live",
            "version": "1.2.0",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "sports",
            "archetype": "ml-sports",
            "inception_date": "2025-03-10",
            "instruments": ["LALIGA_MATCH_ODDS"],
        },
        {
            "id": "strat-044",
            "name": "SPORTS_NBA_MM_EVT_QUARTER",
            "asset_class": "sports",
            "venue": "betfair",
            "status": "staging",
            "version": "0.7.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "sports",
            "archetype": "market-making",
            "inception_date": "2025-10-15",
            "instruments": ["NBA_MONEYLINE", "NBA_SPREAD"],
        },
        {
            "id": "strat-045",
            "name": "SPORTS_MLB_VALUE_BET_EVT_GAME",
            "asset_class": "sports",
            "venue": "matchbook",
            "status": "paper",
            "version": "0.4.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "sports",
            "archetype": "value-betting",
            "inception_date": "2025-12-01",
            "instruments": ["MLB_MONEYLINE", "MLB_RUN_LINE"],
        },
        {
            "id": "strat-046",
            "name": "SPORTS_SERIE_A_ARB_EVT_MATCH",
            "asset_class": "sports",
            "venue": "betfair",
            "status": "development",
            "version": "0.1.0",
            "org_id": _B,
            "client_id": _CLIENT_BETA,
            "desk": "sports",
            "archetype": "arbitrage",
            "inception_date": "2026-02-15",
            "instruments": ["SERIE_A_MATCH_ODDS"],
        },
        # ══════════════════════════════════════════════════════════════
        #  Prediction — 2 new (3 total with 1 legacy)
        # ══════════════════════════════════════════════════════════════
        {
            "id": "strat-047",
            "name": "PREDICTION_POLY_ML_DIR_EVT_4H",
            "asset_class": "prediction",
            "venue": "polymarket",
            "status": "live",
            "version": "1.1.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "quant-fund",
            "archetype": "ml-sports",
            "inception_date": "2025-07-20",
            "instruments": ["POLY_CPI_PRINT", "POLY_NFP_ABOVE"],
        },
        {
            "id": "strat-048",
            "name": "PREDICTION_POLY_ARB_EVT_1H",
            "asset_class": "prediction",
            "venue": "polymarket",
            "status": "staging",
            "version": "0.6.0",
            "org_id": _A,
            "client_id": _CLIENT_ACME,
            "desk": "quant-fund",
            "archetype": "arbitrage",
            "inception_date": "2025-09-05",
            "instruments": ["POLY_ETH_ABOVE_5K", "POLY_BTC_ABOVE_100K"],
        },
        # ══════════════════════════════════════════════════════════════
        #  Extra CeFi + TradFi to round out org distribution
        # ══════════════════════════════════════════════════════════════
        {
            "id": "strat-049",
            "name": "CEFI_MATIC_MOMENTUM_SCE_2H",
            "asset_class": "cefi",
            "venue": "okx",
            "status": "development",
            "version": "0.2.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "momentum",
            "inception_date": "2026-03-01",
            "instruments": ["MATIC/USDT"],
        },
        {
            "id": "strat-050",
            "name": "CEFI_SUI_MOMENTUM_HUF_1H",
            "asset_class": "cefi",
            "venue": "binance",
            "status": "live",
            "version": "1.0.0",
            "org_id": _O,
            "client_id": _CLIENT_ODUM,
            "desk": "delta-one",
            "archetype": "momentum",
            "inception_date": "2025-12-10",
            "instruments": ["SUI/USDT"],
        },
    ]


def generate_strategies() -> list[dict[str, object]]:
    """Return all 50 strategies: 18 legacy + 32 new.

    Distribution summary:
      - Asset class: CeFi 16, TradFi 11, DeFi 11, Sports 9, Prediction 3
      - Org: odum-internal 30, acme 9, vertex 6, beta 5
      - Status: live 32, staging 8, paper 5, development 5
    """
    return _legacy_strategies() + _new_strategies()
